"""Render explicitly selected Clang comment ASTs as shared Python/C++ docs."""

import argparse
import json
import re
import subprocess
from pathlib import Path


def render(node: dict) -> str:
    """Render the supported Doxygen subset; reject unhandled markup."""
    kind = node["kind"]
    children = node.get("inner", [])
    if kind == "TextComment":
        return node["text"]
    if kind == "ParagraphComment":
        # Clang keeps each source line in a TextComment. Retain relative
        # indentation for reStructuredText lists and literal blocks.
        return "\n".join(render(child).removeprefix(" ") for child in children).strip(
            "\n"
        )
    if kind == "FullComment":
        return "\n\n".join(
            text for child in children if (text := render(child)).strip()
        )
    body = "\n\n".join(render(child) for child in children).strip()
    if kind == "ParamCommandComment":
        if "paramIdx" not in node:
            raise ValueError(f"Unknown parameter in documentation: {node['param']}")
        return f":param {node['param']}: " + body.replace("\n", "\n    ")
    if kind == "BlockCommandComment":
        name = node["name"]
        if name in {"brief", "details"}:
            return body
        if name in {"return", "returns", "result"}:
            return ":returns: " + body.replace("\n", "\n    ")
        if name in {"note", "warning"}:
            return f".. {name}::\n\n    " + body.replace("\n", "\n    ")
    raise ValueError(f"Unsupported Doxygen node {kind}: {node.get('name', '')}")


def extract(ast: dict, manifest: dict[str, dict[str, str]]) -> dict[str, str]:
    """Resolve each qualified name and exact Clang signature once."""
    matches = {key: [] for key in manifest}

    def visit(node: dict, scope: tuple[str, ...] = ()) -> None:
        kind = node.get("kind")
        name = node.get("name", "")
        qualified = "::".join((*scope, name))
        for key, selection in manifest.items():
            if (
                qualified == selection["symbol"]
                and node.get("type", {}).get("qualType") == selection["signature"]
            ):
                comments = [
                    child
                    for child in node.get("inner", [])
                    if child.get("kind") == "FullComment"
                ]
                if len(comments) != 1:
                    raise ValueError(f"Missing documentation for {qualified}")
                matches[key].append(render(comments[0]))
        if kind in {"NamespaceDecl", "CXXRecordDecl"} and name:
            scope = (*scope, name)
        for child in node.get("inner", []):
            visit(child, scope)

    visit(ast)
    result = {}
    selections = set()
    for key, selection in manifest.items():
        if not re.fullmatch(r"[A-Z][A-Z0-9_]*", key):
            raise ValueError(f"Invalid documentation identifier: {key}")
        identity = (selection["symbol"], selection["signature"])
        if identity in selections:
            raise ValueError(f"Duplicate documentation selection: {identity}")
        selections.add(identity)
        if len(matches[key]) != 1 or not matches[key][0]:
            raise ValueError(
                f"Expected one documented declaration for {key}: {selection}"
            )
        result[key] = matches[key][0]
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--compiler", required=True)
    parser.add_argument("--header", type=Path, required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--cpp-output", type=Path, required=True)
    parser.add_argument("--python-output", type=Path, required=True)
    parser.add_argument("flags", nargs=argparse.REMAINDER)
    args = parser.parse_args()
    flags = args.flags[1:] if args.flags[:1] == ["--"] else args.flags
    command = [
        args.compiler,
        *flags,
        "-x",
        "c++",
        "-fsyntax-only",
        "-Werror=documentation",
        "-Wno-pragma-once-outside-header",
        "-Xclang",
        "-ast-dump=json",
        str(args.header),
    ]
    result = subprocess.run(command, check=True, stdout=subprocess.PIPE, text=True)
    docs = extract(json.loads(result.stdout), json.loads(args.manifest.read_text()))
    cpp = [
        "// Generated by //tools/docs:extract. Do not edit.",
        "#pragma once",
        "",
        "namespace robo_arch::docstrings {",
    ]
    python = ['"""Generated by //tools/docs:extract. Do not edit."""', ""]
    for key, value in sorted(docs.items()):
        literal = json.dumps(value, ensure_ascii=True)
        cpp.append(f"inline constexpr char {key}[] = {literal};")
        python.append(f"{key} = (")
        for line in value.splitlines(keepends=True):
            python.append("    " + json.dumps(line, ensure_ascii=True))
        python.append(")")
    cpp.append("}  // namespace robo_arch::docstrings")
    args.cpp_output.write_text("\n".join(cpp) + "\n")
    args.python_output.write_text("\n".join(python) + "\n")


if __name__ == "__main__":
    main()
