load("@rules_python//python:defs.bzl", "py_library")

filegroup(
    name = "resources",
    srcs = ["system.yaml"],
    visibility = ["//src/robo_arch:__subpackages__"],
)

py_library(
    name = "ur7e_ideal_camera",
    srcs = ["__init__.py"],
    data = [":resources"],
    visibility = ["//src/robo_arch:__subpackages__"],
    deps = ["//src/robo_arch/robot_system"],
)
