load("@buildifier_prebuilt//:rules.bzl", "buildifier")
load("@hedron_compile_commands//:refresh_compile_commands.bzl", "refresh_compile_commands")

refresh_compile_commands(
    name = "refresh_compile_commands",
    targets = [
        "//src/...",
        "//tests/...",
        "//tools/...",
    ],
)

exports_files(
    ["uv.lock"],
    visibility = ["//visibility:private"],
)

buildifier(
    name = "buildifier",
    exclude_patterns = [
        "./.git/*",
        "./.venv*/*",
        "./deployment/*/.venv*/*",
        "./third_party/*/.venv*/*",
        "./bazel-*/*",
    ],
    lint_mode = "warn",
    mode = "check",
)
