load("@python_deps//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "model_test",
    srcs = ["test_model.py"],
    main = "test_model.py",
    tags = ["drake"],
    deps = [
        "//src/robo_arch/robots/ur7e",
        "//src/robo_arch/robots/ur7e/drake",
        requirement("drake"),
        requirement("numpy"),
        requirement("pytest"),
    ],
)
