load("@python_deps//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library", "py_test")

py_library(
    name = "schema",
    srcs = [
        "__init__.py",
        "schema.py",
    ],
    visibility = ["//src/robo_arch:__subpackages__"],
    deps = [
        "//src/robo_arch/core",
        requirement("pydantic"),
    ],
)

py_library(
    name = "resources",
    srcs = ["resources.py"],
    visibility = ["//src/robo_arch:__subpackages__"],
    deps = [":schema"],
)

py_library(
    name = "config",
    srcs = [
        "cli.py",
        "declarations.py",
        "loading.py",
        "parameters.py",
        "worlds.py",
    ],
    visibility = [
        "//src/robo_arch:__subpackages__",
        "//tests/build:__pkg__",
        "//tools:__pkg__",
    ],
    deps = [
        ":resources",
        ":schema",
        "//src/robo_arch/core/worlds/drake:config",
        "//src/robo_arch/core/worlds/isaac:config",
        "//src/robo_arch/core/worlds/real:config",
        requirement("pydantic"),
        requirement("pyyaml"),
    ],
)

py_test(
    name = "loading_test",
    srcs = ["tests/test_loading.py"],
    main = "tests/test_loading.py",
    deps = [
        ":config",
        requirement("pydantic"),
        requirement("pytest"),
        requirement("pyyaml"),
    ],
)

py_test(
    name = "worlds_test",
    srcs = ["tests/test_worlds.py"],
    main = "tests/test_worlds.py",
    deps = [
        ":config",
        "//src/robo_arch/core/worlds/drake:config",
        "//src/robo_arch/core/worlds/isaac:config",
        "//src/robo_arch/core/worlds/real:config",
        requirement("pydantic"),
        requirement("pytest"),
    ],
)

py_test(
    name = "cli_test",
    srcs = ["tests/test_cli.py"],
    main = "tests/test_cli.py",
    deps = [
        ":config",
        requirement("pydantic"),
        requirement("pytest"),
    ],
)
