"""Read compatibility policy while leaving versions in existing lock/toolchain files."""

import platform
import re
import shutil
import subprocess
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def metadata(root: Path = ROOT) -> dict:
    with (root / "third_party/compatibility.toml").open("rb") as file:
        return tomllib.load(file)


def profile(name: str, root: Path = ROOT) -> dict:
    record = dict(metadata(root)["profiles"][name])
    record["python_version"] = (root / record["python"]).read_text().strip()
    return record


def check_host(record: dict) -> None:
    """Fail unsupported hosts; never install packages, drivers or Apple SDKs."""
    if (platform.system(), platform.machine()) != (
        record["system"],
        record["architecture"],
    ):
        raise RuntimeError(
            f"Profile requires {record['os']} / {record['architecture']}"
        )
    if platform.system() == "Linux":
        release = platform.freedesktop_os_release()
        if (release.get("ID"), release.get("VERSION_ID")) != ("ubuntu", "24.04"):
            raise RuntimeError("Initial Linux profiles require Ubuntu 24.04")
    elif int(platform.mac_ver()[0].split(".")[0]) < 15:
        raise RuntimeError("Drake profile requires macOS 15 or newer")
    for program in ("uv", "bazel", "git"):
        if shutil.which(program) is None:
            raise FileNotFoundError(f"Install host prerequisite: {program}")
    if platform.system() == "Darwin":
        subprocess.run(["xcrun", "--show-sdk-path"], check=True)


def check_pins(root: Path = ROOT) -> None:
    """Detect divergent interpreter declarations without introducing a resolver."""
    module = (root / metadata(root)["module"]).read_text()
    bazelrc = (root / ".bazelrc").read_text()
    for name in ("ubuntu", "macos"):
        version = profile(name, root)["python_version"]
        if (
            len(
                re.findall(r'python_version\s*=\s*"' + re.escape(version) + '"', module)
            )
            != 2
        ):
            raise ValueError(f"{name}: pin must match Bazel toolchain and pip.parse")
        if name == "macos" and f"python_version={version}" not in bazelrc:
            raise ValueError("macOS Bazel interpreter flag differs from profile pin")


def sync_command(record: dict, *, check: bool = False) -> list[str]:
    command = [
        "uv",
        "sync",
        "--locked",
        "--project",
        record["project"],
        "--python",
        record["python_version"],
        "--no-default-groups",
    ]
    for group in record["groups"]:
        command.extend(["--group", group])
    if check:
        # The Bazel-built native wheel is deliberately outside the Python lock.
        command.extend(["--check", "--inexact"])
    return command


def support_table(root: Path = ROOT) -> str:
    lines = [
        "<!-- Generated by python -m tools.validation matrix; edit compatibility.toml. -->",
        "| Profile | Host | Python | Lock | Evidence |",
        "|---|---|---|---|---|",
    ]
    for name in metadata(root)["profiles"]:
        item = profile(name, root)
        lines.append(
            f"| {name} | {item['os']} / {item['architecture']} | "
            f"{item['python_version']} | `{item['lock']}` | {item['evidence']} |"
        )
    return "\n".join(lines) + "\n"
