load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library", "py_test")

py_library(
    name = "contracts",
    srcs = [
        "__init__.py",
        "components.py",
        "ports.py",
    ],
    visibility = ["//src/robo_arch:__subpackages__"],
    deps = [
        "//src/robo_arch",
        requirement("pydantic"),
    ],
)

py_test(
    name = "contracts_test",
    srcs = ["tests/test_contracts.py"],
    main = "tests/test_contracts.py",
    deps = [
        ":contracts",
        "//src/robo_arch/config",
        requirement("pydantic"),
        requirement("pytest"),
    ],
)
