"""Export hashed Bazel inputs from uv.lock; --check never changes checked-in files."""

import argparse
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for profile in ("core", "drake"):
        command = [
            "uv",
            "export",
            "--locked",
            "--format",
            "requirements-txt",
            "--no-default-groups",
            "--group",
            "test",
            "--no-emit-project",
            "--no-header",
            "--no-annotate",
        ]
        if profile == "drake":
            command.extend(["--group", "drake"])
        result = subprocess.run(
            command, cwd=ROOT, check=False, capture_output=True, text=True
        )
        if result.returncode:
            raise SystemExit(result.stderr)
        content = (
            "# Generated by tools/export_requirements.py from uv.lock.\n"
            + result.stdout
        )
        path = ROOT / "third_party" / "python" / f"{profile}.txt"
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content)
    if stale:
        raise SystemExit("Stale exports: " + ", ".join(stale))


if __name__ == "__main__":
    main()
