load("@python_deps//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library", "py_test")

py_library(
    name = "package",
    srcs = ["__init__.py"],
    visibility = ["//src/robo_arch:__subpackages__"],
    deps = ["//src/robo_arch/core"],
)

py_library(
    name = "worlds",
    srcs = [
        "assembly.py",
        "devices.py",
        "traces.py",
        "urdf.py",
    ],
    visibility = ["//src/robo_arch:__subpackages__"],
    deps = [
        ":package",
        requirement("numpy"),
        requirement("matplotlib"),
        "//src/robo_arch/core/config",
    ],
)

py_test(
    name = "assembly_test",
    srcs = ["tests/test_assembly.py"],
    main = "tests/test_assembly.py",
    deps = [
        ":worlds",
        "//src/robo_arch/core/config",
        "//src/robo_arch/core/worlds/drake:config",
        requirement("pytest"),
    ],
)

py_test(
    name = "devices_test",
    srcs = ["tests/test_devices.py"],
    main = "tests/test_devices.py",
    deps = [
        ":worlds",
        "//src/robo_arch/core/config",
        "//src/robo_arch/core/worlds/drake:config",
        "//src/robo_arch/core/worlds/isaac:config",
        "//src/robo_arch/core/worlds/real:config",
        "//src/robo_arch/objects/box",
        "//src/robo_arch/robots/ur7e",
        "//src/robo_arch/sensors/realsense_d435",
        requirement("pydantic"),
        requirement("pytest"),
    ],
)
