load("@python_deps//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library", "py_test")

py_library(
    name = "package",
    srcs = ["__init__.py"],
    visibility = ["//src/robo_arch:__subpackages__"],
    deps = ["//src/robo_arch/core"],
)

py_library(
    name = "assembly",
    srcs = ["assembly.py"],
    visibility = ["//src/robo_arch:__subpackages__"],
    deps = [
        ":package",
        "//src/robo_arch/core/config",
    ],
)

py_library(
    name = "devices",
    srcs = ["devices.py"],
    visibility = [
        "//src/robo_arch:__subpackages__",
        "//tests/build:__pkg__",
    ],
    deps = [
        ":assembly",
        "//src/robo_arch/core/config",
    ],
)

py_library(
    name = "worlds",
    srcs = ["urdf.py"],
    visibility = ["//src/robo_arch:__subpackages__"],
    deps = [
        ":assembly",
        ":devices",
        ":package",
        requirement("drake"),
        "//src/robo_arch/core/config",
    ],
)

py_test(
    name = "assembly_test",
    srcs = ["tests/test_assembly.py"],
    main = "tests/test_assembly.py",
    deps = [
        ":worlds",
        "//src/robo_arch/core/config",
        "//src/robo_arch/core/worlds/drake:config",
        requirement("pytest"),
    ],
)

py_test(
    name = "devices_test",
    srcs = ["tests/test_devices.py"],
    main = "tests/test_devices.py",
    deps = [
        ":worlds",
        "//src/robo_arch/core/config",
        "//src/robo_arch/core/worlds/drake:config",
        "//src/robo_arch/core/worlds/isaac:config",
        "//src/robo_arch/core/worlds/real:config",
        "//src/robo_arch/objects/box",
        "//src/robo_arch/robots/ur7e",
        "//src/robo_arch/sensors/realsense_d435",
        requirement("pydantic"),
        requirement("pytest"),
    ],
)

py_test(
    name = "robot_assets_test",
    srcs = ["tests/test_robot_assets.py"],
    main = "tests/test_robot_assets.py",
    deps = [
        ":worlds",
        "//src/robo_arch/core/config",
        "//src/robo_arch/core/worlds/drake",
        requirement("drake"),
        requirement("pytest"),
    ],
)

py_test(
    name = "poses_test",
    srcs = ["tests/test_poses.py"],
    main = "tests/test_poses.py",
    deps = [
        ":worlds",
        "//src/robo_arch/core/config",
        requirement("numpy"),
        requirement("pytest"),
    ],
)

py_library(
    name = "launch",
    srcs = ["launch.py"],
    visibility = [
        "//src/robo_arch:__subpackages__",
        "//tools:__pkg__",
    ],
    deps = [":package"],
)

py_test(
    name = "launch_test",
    srcs = ["tests/test_launch.py"],
    main = "tests/test_launch.py",
    deps = [
        ":launch",
        requirement("pytest"),
    ],
)
